version: 0.2

env:
  variables:
    TABLE_NAME: "iot-dynamodb-IotDemoTable-1096ZA2SMLFQC"
    S3_BUCKET: "shuntagami-iot-data"

phases:
  install:
    commands:
      - pip install pytest
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sh buildspec_files/test_sqs_to_dynamo.sh
